### ISSUE TITLE
gnupg_verify does not verify clearsign messages

### ISSUE THREAD

**Issue by jaw-sh** [php-gnupg/php-gnupg#18]
`gnupg_verify` incorrectly asserts spoofed clearsigned messages are legitimate (php7.3, debian10)

[pgp_real.txt](https://github.com/php-gnupg/php-gnupg/files/4512547/pgp_real.txt)
```
gpg --verify pgt_real.txt 
gpg: Signature made Tue 21 Apr 2020 08:40:27 AM EDT
gpg:                using RSA key 8E570D9F7F70256595769E49F9BC5BCAD7E18635
gpg: Good signature from "Joshua" [ultimate]
```

[pgp_spoof.txt](https://github.com/php-gnupg/php-gnupg/files/4512543/pgp_spoof.txt)
```
#gpg --verify pgt_spoof_sig.txt 
gpg: Signature made Tue 21 Apr 2020 08:40:27 AM EDT
gpg:                using RSA key 8E570D9F7F70256595769E49F9BC5BCAD7E18635
gpg: BAD signature from "Joshua" [ultimate]
```

```
<?php

$gnupg = gnupg_init();
$verify = gnupg_verify($gnupg, file_get_contents('pgt_real.txt'), false);

if (is_array($verify)) {
    echo "you're right, having fun online is awesome.\n";
}

$verify = gnupg_verify($gnupg, file_get_contents('pgt_spoof_sig.txt'), false);

if ($verify !== false) {
    echo "What? you don't like having fun online? this can't be a real message\n";
}
```

Output:
```
you're right, having fun online is awesome.
What? you don't like having fun online? this can't be a real message
```

**Comment by bukka** [comment]
Apology for the late reply but has this been resolved. The thing that comes to my mind is a different home directory. That could be now (since extension version 1.5) set explicitly in constructor like here https://github.com/php-gnupg/php-gnupg/blob/gnupg-1.5.0/tests/gnupg_oo_init_home_dir.phpt#L13

**Comment by bukka** [comment]
Closing as there has not been any reply and the new options are now also documented: https://www.php.net/manual/en/function.gnupg-init.php

f you still see an issue with version 1.5, please open a new issue.
