### ISSUE TITLE
'add_next_index_zval' was replaced in PHP 7.4+ and PHP 8

### ISSUE THREAD

**Issue by DRRDietrich** [php-gnupg/php-gnupg#20]
[See commit on Github](https://github.com/php/php-src/commit/85e1df6fdcaf307c5e6b241df4d859e916806d2a)

This caused the following problem:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'gnupg.so' (tried: /usr/lib64/php/modules/gnupg.so (/usr/lib64/php/modules/gnupg.so: undefined symbol: add_next_index_zval)`

- [ ] Replace `add_next_index_zval` with new macro

**Comment by bukka** [comment]
Fixed since 1.5.0RC1
