### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by sartor** [php-gnupg/php-gnupg#22]
No there is not official build of gnupg library for PHP8.
Do you have any roadmap when it will be released?

**Comment by bukka** [comment]
Yeah working on it which is being pushed to my next branch: https://github.com/php-gnupg/php-gnupg/compare/master...bukka:next including some test updates. Needs a bit more work and also need to finialize some tests changes for gpg2 which will be also supported in the next release.

**Comment by aphix-mark** [comment]
This may not be needed if the work from @bukka is about to be merged (work has been done in the past few days so fingers crossed!) but we've created a pull request https://github.com/php-gnupg/php-gnupg/pull/24 branching from 1.4.0 to add PHP8 support.

For us, it's a "drop in replacement" for 1.4.0, so we just bumped it to version 1.4.0

For anyone looking to do the same, we've also created and released the .so which may be helpful, and made it available here:
https://github.com/aphixsoftware/php-gnupg/releases/tag/gnupg-1.41-rc1

As a "short-term-fix" this may be useful and can be rejected after 1.5.0 is ready.

**Comment by sartor** [comment]
Is there any news?

**Comment by bukka** [comment]
There has been already 2 RC's for 1.5 version. You can use those. The stable version should be released in a 3 or 6 weeks depending if there are any further bugs but so far it looks quite stable so think you can start using that.

**Comment by sartor** [comment]
There are still no any builds in Ondrej's (https://launchpad.net/~ondrej/+archive/ubuntu/php) repository. I will wait, thank you.

**Comment by burzum** [comment]
Still no builds...
