### ISSUE TITLE
Can't get php-gnupg to work

### ISSUE THREAD

**Issue by Spitfireap** [php-gnupg/php-gnupg#31]
Hi, 
I tried the nextcloud GPG Mailer extension and I can't get it to work due to an issue with the php gnupg module it seems (see issue https://github.com/tacruc/gpgmailer/issues/20).
The server is running in Freebsd 12 with apache24 and php-fpm. Php version is 7.4.  Apache as well as php-fpm work with www user. 
The extension is activated and loaded, but if I call any function I get an error even with the smallest example : 
<?php
// /mnt/data is owned by www user as well as .gnupg
// .gnupg has 700 permission and 777 doesn't change anything...
putenv('GNUPGHOME=/mnt/data/.gnupg/');
error_reporting(E_ALL);
$res = gnupg_init();
gnupg_seterrormode($res,GNUPG_ERROR_WARNING);
$info = gnupg_keyinfo($res, 'your-key-id');
echo "Key - Info<pre>";
var_dump($info);
echo "</pre>";
?>
I get `Key - Info
bool(false)`
and in the httpd-error I have : 
`[Wed May 19 15:29:04.026882 2021] [proxy_fcgi:error] [pid 28899] [client XX.XX.xx.XX:32476] AH01071: Got error 'PHP message: PHP Warning:  gnupg_keyinfo(): could not init keylist in /usr/local/www/test/test.php on line 6'`

also weird thing is the return of gnupg_getengineinfo($res) : 
`(
    [protocol] => 6
    [file_name] => /nonexistent
    [home_dir] => 
)`

What is going wrong ? 

Thanks for your help,
Adrien

**Comment by bukka** [comment]
Sorry for the later reply. Is this still an issue? If so, have you tried to change home with constructor param like in https://github.com/php-gnupg/php-gnupg/blob/gnupg-1.5.0/tests/gnupg_oo_init_home_dir.phpt#L13 ?

**Comment by gRegorLove** [comment]
I'm experiencing similar with trying to encrypt using a public key. I think it's related to the Apache `nobody` user vs different owner of `~/.gnupg/`.

Setting `home_dir` in the constructor "works" in that it shows up in the engine info, but still does not seem to be able to load the key:

```php
$gpg = new gnupg(['home_dir' => '/usr/home/example/.gnupg']);
$gpg->seterrormode(gnupg::ERROR_WARNING);
$engine = $gpg->getengineinfo();
print_r($engine);
```

Output:
```
Array
(
    [protocol] => 0
    [file_name] => /usr/bin/gpg
    [home_dir] => /usr/home/example/.gnupg
)
```

Then if I try:

```php
$gpg = new gnupg(['home_dir' => '/usr/home/example/.gnupg']);
$gpg->seterrormode(gnupg::ERROR_WARNING);
$gpg->addencryptkey($fingerprint); # I have double-checked $fingerprint is correct
```

Result:

```
Warning: gnupg::addencryptkey(): get_key failed
```

I have also tried importing the public key from a local directory (not `~/.gnupg`):

```php
$gpg = new gnupg(['home_dir' => '/usr/home/example/.gnupg']);
$gpg->seterrormode(gnupg::ERROR_WARNING);

$public_key = file_get_contents( dirname(__DIR__) . '/public.key' );
$info = $gpg->import($public_key);
var_dump($info);
```

Result: `bool(false)`

I've verified the public key is being read correctly and is in $public_key, so not sure what's causing it to return false.

I'm looking for a solution without needing to make `~/.gnupg` fully read-writable by the `nobody` user. Thanks in advance for any suggestions!

**Comment by bukka** [comment]
@gRegorLove If this is for gpg2, then you can try to check the permissions for `/usr/home/example/.gnupg/private-keys-v1.d/`? It needs to be 0700. If this is ok, could you post the output of `var_dump($gpg->geterrorinfo());` after the failing import?

**Comment by gRegorLove** [comment]
@bukka It's been a bit since I worked on this, but yes I think we got it working based on file permissions. It is gpg2 and `private-keys-v1.d` is 0700. 👍
