### ISSUE TITLE
Unknown value 0 for status/summary in decryptverify()

### ISSUE THREAD

**Issue by ZeiP** [php-gnupg/php-gnupg#34]
I'm trying to decrypt and verify a GPG-encrypted message with the following code:

```
  /**
   * Decrypt the given data with the given keys.
   *
   * @param string $str
   *   The data to encrypt.
   *
   * @return string
   *   The decrypted data as a string.
   */
  public function decryptData($str) {
    $gpg = new \gnupg();
    $gpg->seterrormode(\gnupg::ERROR_EXCEPTION);
    $res = $gpg->decryptverify($str, $data);
    $gpg = NULL;

    if ($res[0]['validity'] !== \gnupg::VALIDITY_NEVER && $res[0]['summary'] & \gnupg::SIGSUM_VALID) {
      return $data;
    }

    return FALSE;
  }
```

However, what I get as $res is:
```
array(1) {
  [0]=>
  array(5) {
    ["fingerprint"]=>
    string(40) "[CORRECT SIGN KEY FINGERPRINT]"
    ["validity"]=>
    int(0)
    ["timestamp"]=>
    int(1628028914)
    ["status"]=>
    int(0)
    ["summary"]=>
    int(0)
  }
}
```

Per documentation I'd expect the status and summary fields to contain a value compatible with one of the status constants, but instead I'm getting a 0 which doesn't seem to be documented anywhere. What does 0 as status/summary mean?

When I decrypt the same message with gpg --decrypt, I get the correct message and the signature information as follows:
```
gpg: Signature made Tue Aug  3 22:15:14 2021 UTC using DSA key ID XXXXXXXXX
gpg: Good signature from "[email]"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

**Comment by bukka** [comment]
The validity is an integer value that comes from gpgme library. There's no string representation of those. Instead you are supposed to compare it against the existing constants (using `switch` for example). If you just want to get the meaning of the values for your own convenience, you can see that in gpgme: https://github.com/gpg/gpgme/blob/ac4536990a4fed4a45a0851260c029e69d0cadf6/src/gpgme.h.in#L317-L326 . In your case it means that the validity is unknown.
