### ISSUE TITLE
How can i install php-gnupg extension?

### ISSUE THREAD

**Issue by shaxkiko** [php-gnupg/php-gnupg#39]
After I added ```extension=gnupg``` in php.ini,

I made test.php.

```
<?php
error_reporting( E_ALL );
ini_set( "display_errors", 1 );

putenv("GNUPGHOME=/home/james/.gnupg");
$gpg = new gnupg();
$gpg -> addencryptkey("RX8894E4B5DF8E9386642D4EE48156B2F9435D62");
$enc = $gpg -> encrypt("just a test");
echo $enc;
?>
```

But It says ```Class "gnupg" not found in /var/www/html/test.php```.....

There were no error in compile. and I founded gnupg.so.

I don't know where problem is..

OS : ubuntu-desktop 64bit
PHP 8.0.8

**Comment by shaxkiko** [comment]
I checked ```php -m | grep gnupg```. It shows ```gnupg```. I think It is installed. But test.php is still showing ``` Fatal error: Uncaught Error: Class "gnupg" not found in /var/www/html/test.php:6 Stack trace: #0 {main} thrown in /var/www/html/test.php on line 6```

**Comment by bukka** [comment]
If this is still an issue, can you please provide output of the below?
```
php -i | grep gnupg -A 3
```

**Comment by bukka** [comment]
I assume that this is no longer problem so closing this issue. Please comment here or open a new issue if you are still experiencing this issue.
