### ISSUE TITLE
private keys issues

### ISSUE THREAD

**Issue by the-djmaze** [php-gnupg/php-gnupg#44]
While working on my issue
https://github.com/the-djmaze/snappymail/issues/89

I am extensively testing this extension and seems to hit a wall.

1. While using `gnupg::import('privatekey')` the process runs for seconds and fails to import.
It seems gpg is waiting for password input but there is no parameter in the function to achieve that.

2. `gnupg::keyinfo('', 1)` (hidden param 1 added in v1.5) should return secret keys but has same behaviour as point 1 and also seems to wait for password input.

Is there anyway to solve these, or should https://php.net/gnupg be updated with warnings regarding private keys?

**Comment by the-djmaze** [comment]
Solved!

Executing `gpg-agent --daemon --homedir /very/long/path/to/.gnupg` gave the error.

> socket name for '/very/long/path/to/.gnupg/S.gpg-agent.extra' is too long

So there must be added a check that homedir + '/S.gpg-agent.extra' is < 107

**Comment by bukka** [comment]
How do you set homedir?

**Comment by bukka** [comment]
I mean do you pass it to constructor or using env var?

**Comment by the-djmaze** [comment]
Use the cpg_init($options) $options parameter

**Comment by fs1** [comment]
Is this issue solved with [6df7b76](https://github.com/the-djmaze/snappymail/commit/6df7b76c8a0206346a986a4b1f9f1f25adc14ad3)?

**Comment by the-djmaze** [comment]
@fs1 yes, but after that there were more fixes/improvements
