### ISSUE TITLE
is_secret property does not seem to be set properly

### ISSUE THREAD

**Issue by travisghansen** [php-gnupg/php-gnupg#5]
`->keyinfo()` seems to always return `false` for the `is_secret` property (even after importing a private key).  Am I missing something or is it just not not functioning properly?

**Comment by travisghansen** [comment]
So I've done some research on this one and it appears the signature of ```->keyinto()``` method does not follow the full feature set of ```gpgme``` functionality.

```— Function: gpgme_error_t gpgme_op_keylist_start (gpgme_ctx_t ctx, const char *pattern, int secret_only)```

The parameter ```secret_only``` is IMO a misnomer.  If set to 0 it returns *only* public keys and not *both* public *and* private.  I could do filtering/merging at the interpreter layer (call the method twice and iterate the results) however if that that part of the signature was exposed to via the extension.

**Comment by bukka** [comment]
I think it makes sense to add an optional parameter to the `keyinfo` to set `secret_only`. Setting milestone to 1.5 for that ;)

**Comment by travisghansen** [comment]
Excellent I'll keep an eye out.  Not really a C guy but if I get ambitious I may try it out myself and submit a PR.

**Comment by bukka** [comment]
This has been implemented in https://github.com/php-gnupg/php-gnupg/commit/d93d6ea80db1e333febe83ff1e3245c3b005ac00 and test added in https://github.com/php-gnupg/php-gnupg/commit/7c040788ad3ccaff70a8983f774e0ffaabf6ae3d . Although the tests will need some improvements eventually...

**Comment by dr2okevin** [comment]
What is the state here? On my fresh install with php7.3 the keyinfo shows me only public keys. In addition, it says always "can_sign" even there where it is not possible.

**Comment by bukka** [comment]
I haven't done a release for quite a long time. Will need to do it when I get a bit more time. For now you can compile it from source if you want the feature now. Something like:
```
git clone https://github.com/php-gnupg/php-gnupg.git
cd php-gnupg
phpize
./configure
make
sudo make install
```
and then enabling extension in php.ini.
