### ISSUE TITLE
support getting key length and algorithm

### ISSUE THREAD

**Issue by travisghansen** [php-gnupg/php-gnupg#6]
Not sure if `gpgme` supports this but if possible I'd like to detect those attributes.  Specifically from the `->keyinfo()` method.

**Comment by travisghansen** [comment]
Also the attribute ```GPGME_ATTR_CAN_CERTIFY```

https://www.gnupg.org/documentation/manuals/gpgme/Information-About-Keys.html

Missing from the list in gpgme is whether or not the key can be used for authentication.  The ```a``` attribute from the cli output.

**Comment by bukka** [comment]
I think that it would be good idea to export more info that is available for key and subkey as documented in:

https://www.gnupg.org/documentation/manuals/gpgme/Key-Management.html#Key-Management

However the ATTR interface is deprecated and will be removed so I'm not going to use that.

**Comment by tacruc** [comment]
Would it be enogh to add the corresponting gpgme atributes in here?
https://github.com/php-gnupg/php-gnupg/blob/c4b82c4deea610e33d56cfe30c2fe65cb1937473/gnupg.c#L883

**Comment by travisghansen** [comment]
@tacruc I believe so yes.  While we're digging into this is might be good to resolve #5 too :)  That would help me reach feature parity with the cli driver for my project over here: https://github.com/travisghansen/phpgpg  There are several other things missing that you can see in the TODO file if you're interested.

**Comment by tacruc** [comment]
@travisghansen the problem is at the moment I don't have a development environment for C and I don't think it makes sense to install it on the tablet I'm traveling with. So at the moment I only can help reading the docs.
