### ISSUE TITLE
Support multiple gnupg home directories

### ISSUE THREAD

**Issue by splagemann** [php-gnupg/php-gnupg#7]
Hi,
I know that I can set the gnupg home directory with an environment variable `GNUPGHOME=/somewhere`.
As I'd like to work with temporary directories and importing the key I need on the fly, it would be awesome to support setting a temporary directory with the gnupg_init() command. That way I can work with a temporary directory and remove that when I'm done.

Thanks

**Comment by bukka** [comment]
Yeah that makes sense. I would like to add a bit more options for selecting engine and also setting the path. Basically what `gpgme_ctx_set_engine_info` allows.

**Comment by bukka** [comment]
This has been recently implemented and it's in the master - the example can be seen in the following tests:
* objective: https://github.com/php-gnupg/php-gnupg/blob/c1666d093cb2c78f8d8ead491ec1734c24399d63/tests/gnupg_oo_init_home_dir.phpt
* resource: https://github.com/php-gnupg/php-gnupg/blob/c1666d093cb2c78f8d8ead491ec1734c24399d63/tests/gnupg_res_init_home_dir.phpt
